const OBS = Object.freeze({
  // Grundelemente
  WORD_FOUND: "WORD_FOUND",
  SENTENCE_FOUND: "SENTENCE_FOUND",

  // Wortarten
  ARTICLE_FOUND: "ARTICLE_FOUND",
  PRONOUN_FOUND: "PRONOUN_FOUND",
  PREPOSITION_FOUND: "PREPOSITION_FOUND",
  CONJUNCTION_FOUND: "CONJUNCTION_FOUND",

  // Nominal- und Präpositionalgruppen
  ARTICLE_NOUN_PATTERN:
    "ARTICLE_NOUN_PATTERN",

  PREPOSITION_ARTICLE_PATTERN:
    "PREPOSITION_ARTICLE_PATTERN",

  PREPOSITION_ARTICLE_NOUN_PATTERN:
    "PREPOSITION_ARTICLE_NOUN_PATTERN",

  // Präpositionen mit festem Kasus
  FIXED_DATIVE_PREPOSITION_UNCERTAIN:
    "FIXED_DATIVE_PREPOSITION_UNCERTAIN",

  FIXED_ACCUSATIVE_PREPOSITION_UNCERTAIN:
    "FIXED_ACCUSATIVE_PREPOSITION_UNCERTAIN",

  // Wechselpräpositionen
  TWO_WAY_PREPOSITION_FOUND:
    "TWO_WAY_PREPOSITION_FOUND",

  TWO_WAY_PREPOSITION_LOCATION:
    "TWO_WAY_PREPOSITION_LOCATION",

  TWO_WAY_PREPOSITION_DIRECTION:
    "TWO_WAY_PREPOSITION_DIRECTION",

  TWO_WAY_LOCATION_UNCERTAIN:
    "TWO_WAY_LOCATION_UNCERTAIN",

  TWO_WAY_DIRECTION_UNCERTAIN:
    "TWO_WAY_DIRECTION_UNCERTAIN",

    // Temporale Präpositionen
TEMPORAL_PREPOSITION_FOUND:
  "TEMPORAL_PREPOSITION_FOUND",

TEMPORAL_DURATION_FOUND:
  "TEMPORAL_DURATION_FOUND",

TEMPORAL_PERIOD_FOUND:
  "TEMPORAL_PERIOD_FOUND",

TEMPORAL_DURATION_UNCERTAIN:
  "TEMPORAL_DURATION_UNCERTAIN",

TEMPORAL_PERIOD_UNCERTAIN:
  "TEMPORAL_PERIOD_UNCERTAIN",

  // Syntax – für spätere Sprints bereits reserviert
  SUBORDINATING_CONJUNCTION_FOUND:
    "SUBORDINATING_CONJUNCTION_FOUND",

  SUBORDINATE_CLAUSE_FOUND:
    "SUBORDINATE_CLAUSE_FOUND",

  MODAL_VERB_PATTERN:
    "MODAL_VERB_PATTERN",

  PERFECT_PATTERN:
    "PERFECT_PATTERN",

  SEPARABLE_VERB_PATTERN:
    "SEPARABLE_VERB_PATTERN",

  SUBORDINATE_VERB_POSITION_UNCERTAIN:
    "SUBORDINATE_VERB_POSITION_UNCERTAIN",

  SENTENCE_BRACKET_UNCERTAIN:
    "SENTENCE_BRACKET_UNCERTAIN"
});