const OBS = Object.freeze({
  // Grundelemente
  WORD_FOUND: "WORD_FOUND",
  SENTENCE_FOUND: "SENTENCE_FOUND",
  COMMA_FOUND: "COMMA_FOUND",
  QUESTION_FOUND: "QUESTION_FOUND",

  // Wortarten
  ARTICLE_FOUND: "ARTICLE_FOUND",
  NOUN_FOUND: "NOUN_FOUND",
  ADJECTIVE_FOUND: "ADJECTIVE_FOUND",
  PRONOUN_FOUND: "PRONOUN_FOUND",
  VERB_FOUND: "VERB_FOUND",
  PREPOSITION_FOUND: "PREPOSITION_FOUND",
  CONJUNCTION_FOUND: "CONJUNCTION_FOUND",

  // Verbformen und Satzstruktur
  FINITE_VERB_FOUND: "FINITE_VERB_FOUND",
  MAIN_CLAUSE_FOUND: "MAIN_CLAUSE_FOUND",
  SUBORDINATE_CLAUSE_FOUND: "SUBORDINATE_CLAUSE_FOUND",
  VERB_SECOND_OBSERVED: "VERB_SECOND_OBSERVED",
  VERB_FINAL_OBSERVED: "VERB_FINAL_OBSERVED",
  SENTENCE_BRACKET_OBSERVED: "SENTENCE_BRACKET_OBSERVED",

  // Nominalgruppen
  ARTICLE_NOUN_PATTERN: "ARTICLE_NOUN_PATTERN",
  ADJECTIVE_NOUN_PATTERN: "ADJECTIVE_NOUN_PATTERN",
  ARTICLE_ADJECTIVE_NOUN_PATTERN:
    "ARTICLE_ADJECTIVE_NOUN_PATTERN",

  // Präpositionalgruppen
  PREPOSITION_ARTICLE_PATTERN:
    "PREPOSITION_ARTICLE_PATTERN",
  PREPOSITION_NOUN_PATTERN:
    "PREPOSITION_NOUN_PATTERN",
  PREPOSITION_ARTICLE_NOUN_PATTERN:
    "PREPOSITION_ARTICLE_NOUN_PATTERN",

  // Verbale Muster
  MODAL_VERB_PATTERN: "MODAL_VERB_PATTERN",
  PERFECT_PATTERN: "PERFECT_PATTERN",
  SEPARABLE_VERB_PATTERN: "SEPARABLE_VERB_PATTERN",
  PASSIVE_PATTERN: "PASSIVE_PATTERN",

  // Nebensätze
  SUBORDINATING_CONJUNCTION_FOUND:
    "SUBORDINATING_CONJUNCTION_FOUND",
  RELATIVE_CLAUSE_PATTERN:
    "RELATIVE_CLAUSE_PATTERN",
  INFINITIVE_ZU_PATTERN:
    "INFINITIVE_ZU_PATTERN"
});
